name: xai-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - dash>=2.9.0
  - pandas>=1.5.0
  - scikit-learn>=1.0.0
  - shap>=0.41.0
  - plotly>=5.13.0
  - numpy>=1.23.0
  - pip>=22.0.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - python-dotenv>=0.21.0
  - pip:
    - dash-bootstrap-components>=1.4.0